### ISSUE TITLE
[Docs] README: add weekly meeting details

### ISSUE THREAD

**Issue by leecalcote** [layer5io/wasm-filters#22]
**Current State:**
A weekly meeting focuses filters (and related topics) found in this repo.

**Desired State:**
Ideally, this readme has a description of and invitation to the weekly meeting (details -https://meet.layer5.io)

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by includestdlibrary** [comment]
> **Current State:**
> A weekly meeting focuses filters (and related topics) found in this repo.
> 
> **Desired State:**
> Ideally, this readme has a description of and invitation to the weekly meeting (details -https://meet.layer5.io)
> 
> **Contributor Resources**
> 
> * [Meshery documentation site](https://meshery.layer5.io/docs/)
> * [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
> * [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

Do I have to add the link of the weekly meetings,time and topic in readme?

**Comment by includestdlibrary** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
That'd be great, @includestdlibrary
