### ISSUE TITLE
Error running the http-auth filter.

### ISSUE THREAD

**Issue by antweiss** [layer5io/wasm-filters#34]
**Description**
Tried running the composition for testing the http-auth filter (which looks a lot like something I've build awhile ago) 
but Envoy crashes when trying to load the WASM module:
```
proxy_1          | [2021-09-13 15:31:21.608][7][critical][main] [external/envoy/source/server/server.cc:96] error initializing configuration '/etc/envoy.yaml': Failed to load WASM module due to an import type mismatch: env.proxy_grpc_call, want: i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 -> i32, but host exports: i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 -> i32
```

**Expected Behavior**
Envoy loads WASM code and runs.

**Environment:**
 - OS: MacOS

**Comment by DelusionalOptimist** [comment]
Hey @antweiss!
@warunicorn19 has fixed this in https://github.com/layer5io/wasm-filters/pull/31 :heavy_check_mark: 
I've merged the PR but please take a look and provide more feedback.

Side note: [This](https://antweiss.com/blog/extending-envoy-with-wasm-and-rust/) was a great blog and helped me get started with Envoy filters. Thank you :smile:

**Comment by antweiss** [comment]
oh, Envoy version.. makes sense
will check

**Comment by antweiss** [comment]
yup 
works like charm
issue can be closed
