### ISSUE TITLE
[CI] Build and release needed for each WASM filter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/wasm-filters#38]
**Current Behavior**
This repo's releases do not contain built binaries of each WASM filter.

**Desired Behavior**
Upon GH release, a binary for each filter should be captured as an artifact.

**Comment by leecalcote** [comment]
@utkarsh-pro ....

**Comment by felixfaisal** [comment]
Hey is this issue open? @leecalcote

**Comment by leecalcote** [comment]
@felixfaisal, yes, indeed. Is this something that you might like to take a stab at?

**Comment by felixfaisal** [comment]
@leecalcote I'd like to give this a try, Need to clarify a few things as I'm confused 
So we need to build the wasm binary, I did not understand that we need to *capture it as an artifact*, Could you elaborate this a bit?

**Comment by leecalcote** [comment]
Sure. Artifacts being the compiled binaries - the items (artifacts) created by the build process need to be saved and released for public consumption. I'm tagging a few others who might assist. @DelusionalOptimist @utkarsh-pro @pranav-bhatt @piyushsingariya @Aisuko @mgfeller

**Comment by felixfaisal** [comment]
Thanks for elaborating @leecalcote 
It would be great if you could assign me this issue, I think I can work on this

**Comment by utkarsh-pro** [comment]
Thanks for taking this up @felixfaisal
