### ISSUE TITLE
Slack Notifier dysfunctional

### ISSUE THREAD

**Issue by leecalcote** [layer5io/wasm-filters#44]
**Description**
See - https://github.com/layer5io/wasm-filters/actions/runs/1659252187

**Comment by theBeginner86** [comment]
@leecalcote 
This is already fixed in my previous [PR](https://github.com/layer5io/wasm-filters/pull/43).

Have a look at the latest workflow run https://github.com/layer5io/wasm-filters/actions/runs/1670343253
I think we can close this one 🤔

**Comment by leecalcote** [comment]
Oh! Excellent. Good. ✔️
