### ISSUE TITLE
Add Release Drafter for the repository

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/wasm-filters#7]
**Current Behavior**
Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Desired Behavior**
Add ReleaseDrafter configuration yaml file & GitHub Action.

---

**Additional Context**
[ReleaseDrafter Configuration File](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[ReleaseDrafter GitHub Action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

**Contributor Resources**

See [layer5 contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by adithyaakrishna** [comment]
@Anita-ihuman Should we just add those files after changing the names and all? If so, I would love to knock out this issue 🚀

**Comment by Anita-ihuman** [comment]
Hi @adithyaakrishna, you are to create a 2 _release-drafter.yml_  files(1 in the GitHub folder and another within the workflow folder) and include in the files the GitHub Action configuration for each. Just as it is done in[ this repository](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)

**Comment by adithyaakrishna** [comment]
Okay Sure, Will Do 💯
