### ISSUE TITLE
Singleton service does not work

### ISSUE THREAD

**Issue by NomadXD** [layer5io/wasm-filters#8]
**Description**
Singleton service causes a segmentation fault when dispatch_http_call is executed after onTick

**Comment by leecalcote** [comment]
Thanks for highlighting this issue, @NomadXD. Is this an issue that you would like to be assigned (to fix)?

**Comment by NomadXD** [comment]
@leecalcote Would like. I'm trying to see what's the issue here. Any idea ? Btw I think the envoy.yaml file needs to be changed. Now singleton service should be added as a bootstrap config.

**Comment by leecalcote** [comment]
FYI @pranav-bhatt @DelusionalOptimist

**Comment by NomadXD** [comment]
@leecalcote The issue is with the bootstrap extension config. The new way of using a wasm singleton is via bootstrap extensions and there was an issue when a http callout occurs. They have fixed it and on master branch. The fix is not there in any of the lastest releases (v1.17.1).

**Comment by DelusionalOptimist** [comment]
> Btw I think the envoy.yaml file needs to be changed. Now singleton service should be added as a bootstrap extension config. (not relevant to the issue)

I think we're still using an old release of istio-proxy here. Ref: [enovy.Dockerfile](https://github.com/layer5io/wasm-filters/blob/master/envoy.Dockerfile).
So probably we shall adopt this new way of configuration once we switch to a newer version of envoy or istio-proxy.

What do you say @pranav-bhatt?

**Comment by pranav-bhatt** [comment]
Yup. There are a ton of hard coded versions sprinkled everywhere that are causing issues similar to what you've pointed out @DelusionalOptimist. According to the [dockerhub page](https://hub.docker.com/r/istio/proxyv2/tags?page=1&ordering=last_updated), 1.9.2 is the latest stable version (corresponding to the actual istio version). Maybe a separate issue to figure this out versioning in general would be amazing.
