### ISSUE TITLE
[Docs] missing documentation for building the rust filters

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/wasm-filters#9]
**Current State:**
The docs have missing instructions on how to build the filters. 

**Desired State:**
Steps for installing the Rust nightly toolchain and the support for WASM compilation target should be added. These are basic requirements for compiling Rust to Wasm.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Excellent call out, @DelusionalOptimist. ✔️
